version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: devpass
       MYSQL_DATABASE: dev-data
       MYSQL_USER: devuser
       MYSQL_PASSWORD: devpass
     ports:
       - '3306:3306'
volumes:
    db_data: {}